# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tdgui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_JanelaPrincipal(object):
    def setupUi(self, JanelaPrincipal):
        JanelaPrincipal.setObjectName("JanelaPrincipal")
        JanelaPrincipal.resize(684, 544)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(JanelaPrincipal.sizePolicy().hasHeightForWidth())
        JanelaPrincipal.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(JanelaPrincipal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.grupoArquivos = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grupoArquivos.sizePolicy().hasHeightForWidth())
        self.grupoArquivos.setSizePolicy(sizePolicy)
        self.grupoArquivos.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.grupoArquivos.setObjectName("grupoArquivos")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.grupoArquivos)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.botaoSelecionarDB = QtWidgets.QPushButton(self.grupoArquivos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botaoSelecionarDB.sizePolicy().hasHeightForWidth())
        self.botaoSelecionarDB.setSizePolicy(sizePolicy)
        self.botaoSelecionarDB.setObjectName("botaoSelecionarDB")
        self.gridLayout.addWidget(self.botaoSelecionarDB, 1, 0, 1, 1)
        self.botaoSelecionarRaiz = QtWidgets.QPushButton(self.grupoArquivos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botaoSelecionarRaiz.sizePolicy().hasHeightForWidth())
        self.botaoSelecionarRaiz.setSizePolicy(sizePolicy)
        self.botaoSelecionarRaiz.setObjectName("botaoSelecionarRaiz")
        self.gridLayout.addWidget(self.botaoSelecionarRaiz, 0, 0, 1, 1)
        self.caminhoDB = QtWidgets.QLineEdit(self.grupoArquivos)
        self.caminhoDB.setAutoFillBackground(True)
        self.caminhoDB.setObjectName("caminhoDB")
        self.gridLayout.addWidget(self.caminhoDB, 1, 1, 1, 1)
        self.botaoSelecionarTemp = QtWidgets.QPushButton(self.grupoArquivos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botaoSelecionarTemp.sizePolicy().hasHeightForWidth())
        self.botaoSelecionarTemp.setSizePolicy(sizePolicy)
        self.botaoSelecionarTemp.setObjectName("botaoSelecionarTemp")
        self.gridLayout.addWidget(self.botaoSelecionarTemp, 2, 0, 1, 1)
        self.caminhoTemp = QtWidgets.QLineEdit(self.grupoArquivos)
        self.caminhoTemp.setAutoFillBackground(True)
        self.caminhoTemp.setObjectName("caminhoTemp")
        self.gridLayout.addWidget(self.caminhoTemp, 2, 1, 1, 1)
        self.raizArquivosTD = QtWidgets.QLineEdit(self.grupoArquivos)
        self.raizArquivosTD.setAutoFillBackground(True)
        self.raizArquivosTD.setObjectName("raizArquivosTD")
        self.gridLayout.addWidget(self.raizArquivosTD, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_5.addWidget(self.grupoArquivos)
        self.grupoLotesTabelas = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grupoLotesTabelas.sizePolicy().hasHeightForWidth())
        self.grupoLotesTabelas.setSizePolicy(sizePolicy)
        self.grupoLotesTabelas.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.grupoLotesTabelas.setObjectName("grupoLotesTabelas")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.grupoLotesTabelas)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.etiquetaPrefixoLote = QtWidgets.QLabel(self.grupoLotesTabelas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.etiquetaPrefixoLote.sizePolicy().hasHeightForWidth())
        self.etiquetaPrefixoLote.setSizePolicy(sizePolicy)
        self.etiquetaPrefixoLote.setObjectName("etiquetaPrefixoLote")
        self.gridLayout_2.addWidget(self.etiquetaPrefixoLote, 0, 0, 1, 1)
        self.campoPrefixoLotes = QtWidgets.QLineEdit(self.grupoLotesTabelas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.campoPrefixoLotes.sizePolicy().hasHeightForWidth())
        self.campoPrefixoLotes.setSizePolicy(sizePolicy)
        self.campoPrefixoLotes.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.campoPrefixoLotes.setAutoFillBackground(True)
        self.campoPrefixoLotes.setObjectName("campoPrefixoLotes")
        self.gridLayout_2.addWidget(self.campoPrefixoLotes, 0, 1, 1, 2)
        self.etiquetaTabela = QtWidgets.QLabel(self.grupoLotesTabelas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.etiquetaTabela.sizePolicy().hasHeightForWidth())
        self.etiquetaTabela.setSizePolicy(sizePolicy)
        self.etiquetaTabela.setObjectName("etiquetaTabela")
        self.gridLayout_2.addWidget(self.etiquetaTabela, 1, 0, 1, 1)
        self.campoTabela = QtWidgets.QLineEdit(self.grupoLotesTabelas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.campoTabela.sizePolicy().hasHeightForWidth())
        self.campoTabela.setSizePolicy(sizePolicy)
        self.campoTabela.setAutoFillBackground(True)
        self.campoTabela.setObjectName("campoTabela")
        self.gridLayout_2.addWidget(self.campoTabela, 1, 1, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout_5.addWidget(self.grupoLotesTabelas)
        self.grupoExecutar = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grupoExecutar.sizePolicy().hasHeightForWidth())
        self.grupoExecutar.setSizePolicy(sizePolicy)
        self.grupoExecutar.setObjectName("grupoExecutar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.grupoExecutar)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.botaoExecutar = QtWidgets.QPushButton(self.grupoExecutar)
        self.botaoExecutar.setObjectName("botaoExecutar")
        self.gridLayout_3.addWidget(self.botaoExecutar, 0, 0, 1, 1)
        self.checkMostrarLog = QtWidgets.QCheckBox(self.grupoExecutar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkMostrarLog.sizePolicy().hasHeightForWidth())
        self.checkMostrarLog.setSizePolicy(sizePolicy)
        self.checkMostrarLog.setChecked(True)
        self.checkMostrarLog.setObjectName("checkMostrarLog")
        self.gridLayout_3.addWidget(self.checkMostrarLog, 0, 1, 1, 1)
        self.barraProgresso = QtWidgets.QProgressBar(self.grupoExecutar)
        self.barraProgresso.setProperty("value", 24)
        self.barraProgresso.setObjectName("barraProgresso")
        self.gridLayout_3.addWidget(self.barraProgresso, 1, 0, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout_5.addWidget(self.grupoExecutar)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.grupoLog = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grupoLog.sizePolicy().hasHeightForWidth())
        self.grupoLog.setSizePolicy(sizePolicy)
        self.grupoLog.setObjectName("grupoLog")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.grupoLog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.caixaLog = QtWidgets.QTextBrowser(self.grupoLog)
        self.caixaLog.setObjectName("caixaLog")
        self.verticalLayout_4.addWidget(self.caixaLog)
        self.gridLayout_4.addWidget(self.grupoLog, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.botaoSelecionarRaiz.raise_()
        self.botaoSelecionarDB.raise_()
        self.botaoSelecionarTemp.raise_()
        self.raizArquivosTD.raise_()
        self.caminhoDB.raise_()
        self.caminhoTemp.raise_()
        self.grupoArquivos.raise_()
        self.raizArquivosTD.raise_()
        self.etiquetaPrefixoLote.raise_()
        self.campoPrefixoLotes.raise_()
        self.etiquetaTabela.raise_()
        self.campoTabela.raise_()
        self.grupoLotesTabelas.raise_()
        self.barraProgresso.raise_()
        self.botaoExecutar.raise_()
        self.checkMostrarLog.raise_()
        self.grupoExecutar.raise_()
        self.grupoLog.raise_()
        JanelaPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JanelaPrincipal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 684, 23))
        self.menubar.setObjectName("menubar")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        JanelaPrincipal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(JanelaPrincipal)
        self.statusbar.setObjectName("statusbar")
        JanelaPrincipal.setStatusBar(self.statusbar)
        self.actionSobre = QtWidgets.QAction(JanelaPrincipal)
        self.actionSobre.setObjectName("actionSobre")
        self.menuInfo.addAction(self.actionSobre)
        self.menubar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(JanelaPrincipal)
        self.checkMostrarLog.toggled['bool'].connect(self.grupoLog.setVisible)
        QtCore.QMetaObject.connectSlotsByName(JanelaPrincipal)

    def retranslateUi(self, JanelaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        JanelaPrincipal.setWindowTitle(_translate("JanelaPrincipal", "MainWindow"))
        self.grupoArquivos.setTitle(_translate("JanelaPrincipal", "Arquivos"))
        self.botaoSelecionarDB.setText(_translate("JanelaPrincipal", "Selecionar banco de dados (.mdb)"))
        self.botaoSelecionarRaiz.setText(_translate("JanelaPrincipal", "Selecionar diretório de arquivos"))
        self.botaoSelecionarTemp.setText(_translate("JanelaPrincipal", "Selecionar arquivo temporário"))
        self.grupoLotesTabelas.setTitle(_translate("JanelaPrincipal", "Lotes e Tabelas"))
        self.etiquetaPrefixoLote.setText(_translate("JanelaPrincipal", "Prefixo dos lotes:"))
        self.etiquetaTabela.setText(_translate("JanelaPrincipal", "Tabela para atualizar Remote_Bid:"))
        self.grupoExecutar.setTitle(_translate("JanelaPrincipal", "Executar"))
        self.botaoExecutar.setText(_translate("JanelaPrincipal", "Atualizar arquivos/remote_bid"))
        self.checkMostrarLog.setText(_translate("JanelaPrincipal", "Mostrar log"))
        self.grupoLog.setTitle(_translate("JanelaPrincipal", "Registro das atividades"))
        self.menuInfo.setTitle(_translate("JanelaPrincipal", "&Extra"))
        self.actionSobre.setText(_translate("JanelaPrincipal", "&Sobre..."))

